config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :fds

  map.resources :rts

  map.resources :schedules

map.connect "schedule/:user_lang", :controller => "sws_static"
map.root :controller => "sws_static", :action => "index"

  

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/fd.rb
class Fd < ActiveRecord::Base
  has_and_belongs_to_many :rts
  def hr
    utc_begin.hour.to_s() + ' to ' + utc_end.hour.to_s() + ' ' + body
  end
end

app/models/rt.rb
class Rt < ActiveRecord::Base
  has_and_belongs_to_many :fds
  has_and_belongs_to_many :schedules
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  has_and_belongs_to_many :rts
end

app/controllers/application.rb
# Filters added to this controller apply to all controllers in the application.
# Likewise, all the methods added will be available for all controllers.

class ApplicationController < ActionController::Base
  helper :all # include all helpers, all the time

  # See ActionController::RequestForgeryProtection for details
  # Uncomment the :secret if you're not using the cookie session store
  protect_from_forgery # :secret => 'fda7130bcca67f819712d46cae1d676f'
  
  # See ActionController::Base for details 
  # Uncomment this to filter the contents of submitted sensitive data parameters
  # from your application log (in this case, all fields with names like "password"). 
  # filter_parameter_logging :password
end

app/controllers/fds_controller.rb
class FdsController < ApplicationController
  # GET /fds
  # GET /fds.xml
  def index
    @fds = Fd.find(:all)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @fds }
    end
  end

  # GET /fds/1
  # GET /fds/1.xml
  def show
    @fd = Fd.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @fd }
    end
  end

  # GET /fds/new
  # GET /fds/new.xml
  def new
    @fd = Fd.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @fd }
    end
  end

  # GET /fds/1/edit
  def edit
    @fd = Fd.find(params[:id])
  end

  # POST /fds
  # POST /fds.xml
  def create
    if params[:fd][:utc_end].strip() == ''
      if params[:fd][:utc_begin].to_i() == 23
        params[:fd][:utc_end] = 0
      else
        params[:fd][:utc_end] = (params[:fd][:utc_begin].to_i() * 10000) + 10000
      end
    end
    @fd = Fd.new(params[:fd])

    respond_to do |format|
      if @fd.save
        flash[:notice] = 'Fd was successfully created.'
        format.html { redirect_to(@fd) }
        format.xml  { render :xml => @fd, :status => :created, :location => @fd }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @fd.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /fds/1
  # PUT /fds/1.xml
  def update
    @fd = Fd.find(params[:id])

    respond_to do |format|
      if @fd.update_attributes(params[:fd])
        flash[:notice] = 'Fd was successfully updated.'
        format.html { redirect_to(@fd) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @fd.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /fds/1
  # DELETE /fds/1.xml
  def destroy
    @fd = Fd.find(params[:id])
    @fd.destroy

    respond_to do |format|
      format.html { redirect_to(fds_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/rts_controller.rb
class RtsController < ApplicationController
  # GET /rts
  # GET /rts.xml
  def index
    @rts = Rt.find(:all)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @rts }
    end
  end

  # GET /rts/1
  # GET /rts/1.xml
  def show
    @rt = Rt.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @rt }
    end
  end

  # GET /rts/new
  # GET /rts/new.xml
  def new
    @rt = Rt.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @rt }
    end
  end

  # GET /rts/1/edit
  def edit
    @rt = Rt.find(params[:id])
  end

  # POST /rts
  # POST /rts.xml
  def create
    @rt = Rt.new(params[:rt])

    respond_to do |format|
      if @rt.save
        flash[:notice] = 'Rt was successfully created.'
        format.html { redirect_to(@rt) }
        format.xml  { render :xml => @rt, :status => :created, :location => @rt }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @rt.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /rts/1
  # PUT /rts/1.xml
  def update
    @rt = Rt.find(params[:id])

    respond_to do |format|
      if @rt.update_attributes(params[:rt])
        flash[:notice] = 'Rt was successfully updated.'
        format.html { redirect_to(@rt) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @rt.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /rts/1
  # DELETE /rts/1.xml
  def destroy
    @rt = Rt.find(params[:id])
    @rt.destroy

    respond_to do |format|
      format.html { redirect_to(rts_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  # GET /schedules
  # GET /schedules.xml
  def index
    @schedules = Schedule.find(:all)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @schedules }
    end
  end

  # GET /schedules/1
  # GET /schedules/1.xml
  def show
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @schedule }
    end
  end

  # GET /schedules/new
  # GET /schedules/new.xml
  def new
    @schedule = Schedule.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @schedule }
    end
  end

  # GET /schedules/1/edit
  def edit
    @schedule = Schedule.find(params[:id])
  end

  # POST /schedules
  # POST /schedules.xml
  def create
    @schedule = Schedule.new(params[:schedule])

    respond_to do |format|
      if @schedule.save
        flash[:notice] = 'Schedule was successfully created.'
        format.html { redirect_to(@schedule) }
        format.xml  { render :xml => @schedule, :status => :created, :location => @schedule }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @schedule.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /schedules/1
  # PUT /schedules/1.xml
  def update
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      if @schedule.update_attributes(params[:schedule])
        flash[:notice] = 'Schedule was successfully updated.'
        format.html { redirect_to(@schedule) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @schedule.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.xml
  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy

    respond_to do |format|
      format.html { redirect_to(schedules_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/sws_static_controller.rb
class SwsStaticController < ApplicationController
  def index
    @schedule = Schedule.find_by_sql("select *, min(datediff(curdate(), posting_date)) from schedules where curdate() > posting_date and language='#{params[:user_lang]}' group by posting_date;")[0]
  end
end

app/helpers/application_helper.rb
# Methods added to this helper will be available to all templates in the application.
module ApplicationHelper
end

app/helpers/fds_helper.rb
module FdsHelper
end

app/helpers/rts_helper.rb
module RtsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/sws_static_helper.rb
module SwsStaticHelper
end

app/views/fds/edit.html.erb
<h1>Editing fd</h1>

<% form_for(@fd) do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :utc_begin %><br />
    <%= select_hour(@fd.utc_begin, :prefix => 'fd[utc_begin]', :discard_type => true) %>
  </p>
  <p>
    <%= f.label :utc_end %><br />
    <%= select_hour(@fd.utc_end, :prefix => 'fd[utc_end]', :include_blank => true, :discard_type => true) %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @fd %> |
<%= link_to 'Back', fds_path %>

app/views/fds/index.html.erb
<h1>Listing fds</h1>

<table>
  <tr>
    <th>Utc begin</th>
    <th>Utc end</th>
    <th>Body</th>
  </tr>

<% for fd in @fds %>
  <tr>
    <td><%=h fd.utc_begin.hour %></td>
    <td><%=h fd.utc_end.hour %></td>
    <td><pre><%=h fd.body %></pre></td>
    <td><%= link_to 'Show', fd %></td>
    <td><%= link_to 'Edit', edit_fd_path(fd) %></td>
    <td><%= link_to 'Destroy', fd, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New fd', new_fd_path %>

app/views/fds/new.html.erb
<h1>New fd</h1>

<% form_for(@fd) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :utc_begin %><br />
    <%= select_hour(0, :prefix => 'fd[utc_begin]', :discard_type => true) %>
  </p>
  <p>
    <%= f.label :utc_end %><br />
    <%= select_hour(nil, :prefix => 'fd[utc_end]', :include_blank => true, :discard_type => true) %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', fds_path %>

app/views/fds/show.html.erb
<p>
  <b>Utc begin:</b>
  <%=h @fd.utc_begin.hour %>
</p>
<p>
  <b>Utc end:</b>
  <%=h @fd.utc_end.hour %>
</p>
<p>
  <b>Body:</b><pre><%= @fd.body %></pre>
</p>


<%= link_to 'Edit', edit_fd_path(@fd) %> |
<%= link_to 'Back', fds_path %>

app/views/layouts/fds.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>Fds: <%= controller.action_name %></title>
  <%= stylesheet_link_tag 'scaffold' %>
</head>
<body>

<p style="color: green"><%= flash[:notice] %></p>

<%= yield  %>

</body>
</html>

app/views/layouts/rts.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>Rts: <%= controller.action_name %></title>
  <%= stylesheet_link_tag 'scaffold' %>
</head>
<body>

<p style="color: green"><%= flash[:notice] %></p>

<%= yield  %>

</body>
</html>

app/views/layouts/schedules.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>Schedules: <%= controller.action_name %></title>
  <%= stylesheet_link_tag 'scaffold' %>
</head>
<body>

<p style="color: green"><%= flash[:notice] %></p>

<%= yield  %>

</body>
</html>

app/views/rts/edit.html.erb
<h1>Editing rt</h1>

<% form_for(@rt) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :utc_offset_column_name %><br />
    <%= f.text_field :utc_offset_column_name %>
  </p>
  <p>
    <%= f.label :utc_offset %><br />
    <%= f.text_field :utc_offset %>
  </p>
  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @rt %> |
<%= link_to 'Back', rts_path %>

app/views/rts/index.html.erb
<h1>Listing rts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Utc offset column name</th>
    <th>Utc offset</th>
  </tr>

<% for rt in @rts %>
  <tr>
    <td><%=h rt.name %></td>
    <td><%=h rt.utc_offset_column_name %></td>
    <td><%=h rt.utc_offset %></td>
    <td><%= link_to 'Show', rt %></td>
    <td><%= link_to 'Edit', edit_rt_path(rt) %></td>
    <td><%= link_to 'Destroy', rt, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New rt', new_rt_path %>

app/views/rts/new.html.erb
<h1>New rt</h1>

<% form_for(@rt) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :utc_offset_column_name %><br />
    <%= f.text_field :utc_offset_column_name %>
  </p>
  <p>
    <%= f.label :utc_offset %><br />
    <%= f.text_field :utc_offset %>
  </p>
  <p><b>Frequency Directives</b><br />
    <%= f.collection_select(:fd_ids, Fd.find(:all, :order => "utc_begin"), :id, :hr, {}, {:name => 'rt[fd_ids][]', :multiple => true}) %>
  </p>
  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', rts_path %>

app/views/rts/show.html.erb
<p>
  <b>Name:</b>
  <%=h @rt.name %>
</p>

<p>
  <b>Utc offset column name:</b>
  <%=h @rt.utc_offset_column_name %>
</p>

<p>
  <b>Utc offset:</b>
  <%=h @rt.utc_offset %>
</p>


<%= link_to 'Edit', edit_rt_path(@rt) %> |
<%= link_to 'Back', rts_path %>

app/views/schedules/edit.html.erb
<h1>Editing schedule</h1>

<% form_for(@schedule) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :year_season %><br />
    <%= f.text_field :year_season %>
  </p>
  <p>
    <%= f.label :language %><br />
    <%= f.text_field :language %>
  </p>
  <p>
    <%= f.label :posting_date %><br />
    <%= f.date_select :posting_date %>
  </p>
  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<h1>Listing schedules</h1>

<table>
  <tr>
    <th>Year season</th>
    <th>Language</th>
    <th>Posting date</th>
  </tr>

<% for schedule in @schedules %>
  <tr>
    <td><%=h schedule.year_season %></td>
    <td><%=h schedule.language %></td>
    <td><%=h schedule.posting_date %></td>
    <td><%= link_to 'Show', schedule %></td>
    <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
    <td><%= link_to 'Destroy', schedule, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<h1>New schedule</h1>

<% form_for(@schedule) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :year_season %><br />
    <%= f.text_field :year_season %>
  </p>
  <p>
    <%= f.label :language %><br />
    <%= f.text_field :language %>
  </p>
  <p>
    <%= f.label :posting_date %><br />
    <%= f.date_select :posting_date %>
  </p>
  <p><b>Regional Tables</b><br />
    <%= f.collection_select(:rt_ids, Rt.find(:all, :order => "created_at"), :id, :name, {}, {:name => 'schedule[rt_ids][]', :multiple => true}) %>
  </p>
  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<p>
  <b>Year season:</b>
  <%=h @schedule.year_season %>
</p>

<p>
  <b>Language:</b>
  <%=h @schedule.language %>
</p>

<p>
  <b>Posting date:</b>
  <%=h @schedule.posting_date %>
</p>


<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>

app/views/sws_static/_get_swsched.html.erb
<p>This app is meant to be an approximation of<br />
<a href='http://www.familyradio.com/international/frame/'>http://www.familyradio.com/international/frame/</a>
</p>
  <% if @schedule %>
    <% @schedule.rts.each do |rt| %>
          <p>
             <table cellpadding='2' cellspacing='1' border='1'><%= rt.name %>
		<tr>
                  <th>UTC</th> 
	<% if rt.utc_offset_column_name.strip() != "" %> 
		  <th><%= rt.utc_offset_column_name %></th>
	<% end %>
		  <th>khz & meter band</th>
		</tr>
	<% rt.fds.each do |fd| %>
	        <tr>
	           <td><%= fd.utc_begin.to_s(:hrmin24) %> to <%= fd.utc_end.to_s(:hrmin24) %></td> 
	    <% if rt.utc_offset_column_name.strip() != "" %> 
		   <td><%= (fd.utc_begin + Integer(rt.utc_offset).hours).to_s(:localize)  %> to <%=  (fd.utc_end + Integer(rt.utc_offset).hours).to_s(:localize) %></td>
            <% end %>
		   <td><pre><%= fd.body %></pre></td>
		</tr>
	<% end %>
             </table>
          </p>
    <% end %>
  <% else %>
There are no schedules to post at this time
  <% end %>

app/views/sws_static/admin.html.erb
<h1>SwsStatic#admin</h1>
<p>Find me in app/views/sws_static/admin.html.erb</p>

app/views/sws_static/index.html.erb
<h1></h1>
<p><%= render :partial => 'get_swsched' %></p>